spring:
  application:
    name: ai-code-helper
  profiles:
    active: local
server:
  port: 8081
  servlet:
    context-path: /api
langchain4j:
  community:
    dashscope:
      chat-model:
        base-url: https://dashscope-intl.aliyuncs.com/api/v1
        model-name: qwen-max
        api-key: <You API Key here>
      embedding-model:
        base-url: https://dashscope-intl.aliyuncs.com/api/v1
        model-name: text-embedding-v4
        api-key: <You API Key here>
      streaming-chat-model:
        base-url: https://dashscope-intl.aliyuncs.com/api/v1
        model-name: qwen-plus
        api-key: <You API Key here>
tavily:
  api-key: <Your Tavily API Key>
